name: Build Minecraft Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discord-logger-template-1.16.5
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: discordlogger-mod-1.16.5
          path: discord-logger-template-1.16.5/build/libs/*.jar
